proxy:
  listen: ":8080"
  routes:
    "/api/test":
      targets:
        - "http://localhost:8081"
        - "http://localhost:8082"
    "/api/users":
      targets:
        - "http://localhost:8083"
        - "http://localhost:8084"
