proxy:
  listen: ":8080"
  routes:
    "/api/test":
      targets:
        - url: "http://localhost:8081"
          weight: 3 # 权重为3，表示每5次请求中约3次转发到这里
        - url: "http://localhost:8082"
          weight: 2 # 权重为2，表示每5次请求中约2次转发到这里
    "/api/users":
      targets:
        - url: "http://localhost:8083"
          weight: 1
        - url: "http://localhost:8084"
          weight: 1

jwt:
  secretKey: "your-secret-key-here"
  exclude:
    - "/health"

rateLimit:
  enable: true
  rate: 5 # 全局默认限流：每秒100个请求
  burst: 3 # 最多允许突发50个请求
  routes:
    "/api/test":
      rate: 2 # 对特定路由限流：每秒10个请求
      burst: 1 # 最多允许突发5个请求
